version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: flashsale-postgres
    ports:
      - "55432:5432"
    env_file:
      - .env.docker
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=flashsale_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: flashsale-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flashsale-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.docker

  flash_sale:
    image: helloworld22123/flash-sale:0.9.0
    container_name: flash-sale
    depends_on:
      - postgres
      - rabbitmq
      - redis
    env_file:
      - .env.docker
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8080:8080"
volumes:
  postgres_data:

